# Generated by Django 4.2.7 on 2023-12-19 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsb',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chsb',
            name='file',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade_number',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='bsb',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='chsb',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
        migrations.AddField(
            model_name='bsb',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.subject'),
        ),
        migrations.AddField(
            model_name='chsb',
            name='subject',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_num',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.grade'),
        ),
    ]
