# Generated by Django 4.2.7 on 2023-12-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_bsb_grade_number_chsb_grade_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
    ]
