# Generated by Django 4.2.7 on 2023-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
