# Generated by Django 4.2.7 on 2023-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsb',
            name='bsb_file',
            field=models.FileField(default='', upload_to='exam/BSB/'),
        ),
        migrations.AddField(
            model_name='chsb',
            name='chsb_file',
            field=models.FileField(default='', upload_to='exam/CHSB/'),
        ),
    ]
