# Generated by Django 4.2.7 on 2023-12-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_bsb_bsb_file_chsb_chsb_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(to='exam.subject'),
        ),
    ]
