# Generated by Django 4.2.7 on 2023-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_grade_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subjects',
            field=models.ManyToManyField(related_name='grades', to='exam.subject'),
        ),
    ]
