# Generated by Django 4.2.7 on 2023-12-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_grade_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='subjects',
        ),
    ]
