version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application -b 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
     

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Specify :ro (read-only)
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
