# Generated by Django 4.2.7 on 2023-11-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='blogs/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(default='', upload_to='blogs/videos/'),
        ),
    ]
