# Generated by Django 4.2.7 on 2023-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.CharField(max_length=255),
        ),
    ]
